apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-site-pvc
  namespace: demo-site
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
