apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-ff1-dev
  namespace: demo-site
spec:
  secretName: demo-ff1-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - demo.ff1.dev
